yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [path('', views.index, name='index'),
               path('group/<slug:slug>/',
                    views.group_posts,
                    name='group_list'),
               path('profile/<str:username>/', views.profile,
                    name='profile'),
               path('posts/<int:post_id>/', views.post_detail,
                    name='post_detail'),
               path('create/', views.post_create,
                    name='post_create'),
               path('posts/<int:post_id>/edit/', views.post_edit,
                    name='post_edit'), ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'), name='index'),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from .validators import validate_not_empty
from django.conf import settings

User = get_user_model()
SYMBOLS = settings.SYMBOLS_FOR_TEXT_POST_STR


class Post(models.Model):
    """
    Класс Post используется для создания моделей Post
    (пост в социальной сети).
    """
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
        max_length=10000,
        validators=[validate_not_empty],
        blank=False
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='postsin',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )

    class Meta:
        """
        Внутренний класс Meta для хранения метаданных
        класса Post.
        """
        ordering = ['-pub_date', '-pk']

    def __str__(self) -> str:
        return self.text[:SYMBOLS]


class Group(models.Model):
    """
    Класс Group используется для создания моделей Group
    сообществ, в которых происходит размещение постов
    в социальной сети.
    """
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    """
    Класс для создания формы, предназначенной для создания нового поста.
    """
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст поста',
            'group': 'Выбрать группу',
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.conf import settings

from .forms import PostForm
from .models import Group, Post

count_per_page = settings.COUNT_PER_PAGE
LETTERS_FOR_TITLE = 30


def index(request):
    """Information which is showing up on the start page."""
    post_list = Post.objects.all()
    paginator = Paginator(post_list, count_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Information for displaying on the page with posts grouped by GROUPS."""
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).all()
    paginator = Paginator(post_list, count_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """
    The view shows a page profile of an authorised user.
    """
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author).all()
    paginator = Paginator(post_list, count_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_quantity = post_list.count()
    context = {
        'author': author,
        'page_obj': page_obj,
        'post_quantity': post_quantity,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """The view shows information about a current post."""
    post_profile = get_object_or_404(Post, pk=post_id)
    title = post_profile.text[:LETTERS_FOR_TITLE]
    context = {
        'post_profile': post_profile,
        'title': title,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """The view creates a new post by a special form."""
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', username=new_post.author)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    """
    This view edits the post by its id and saves changes in database.
    """
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    if author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None, instance=post)
    is_edit = True
    context = {
        'form': form,
        'is_edit': is_edit,
    }

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %} Пост{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Опубликовать новую запись
            {% endif %}                
            {% include 'includes/field_errors.html' %}

            <form method="post" action="{% url 'posts:post_create' %}">
            {% csrf_token %}

            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}               
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>  
              {{ field|addclass:'form-control' }}           
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}   
              </button>
            </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title}}</h1>
    <p>
      <span style="color:green">
        <i>
          <p>{{ group.description }}</p>
        </i>
      </span>
    </p>
    {% for post in page_obj %}
      {% include 'includes/post_feed.html' with display_group_link=False %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}YaTube Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1 class="card-header">Последние обновления на сайте</h1>
    {% for post in page_obj %}
    {% include 'includes/post_feed.html' with display_group_link=True %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ title }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post_profile.pub_date|date:"d E Y" }}
            </li>
          </ul>     
        {% if post_profile.group %}
          <li class="list-group-item">
            Группа: {{ post_profile.group }}
            <a
            href="{% url 'posts:group_list' slug=post_profile.group.slug %}"
            target="_blank">все записи группы</a>
          </li>
        {% endif %}   
          <li class="list-group-item">
            Автор: {{ post_profile.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post_profile.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' username=post_profile.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post_profile.text }}
      </p>
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}    
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ post_quantity }} </h3>   
    <article>
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
         </li>
      </ul>      
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post_id=post.pk %}" class="btn btn-primary">подробная информация </a>
      <p>
      {% if post.group %}
        <a
          href="{% url 'posts:group_list' slug=post.group.slug %}"
          class="btn btn-primary"
          target="_blank">Группа</a>
      {% endif %}
      </p>
      {% endfor %}
    </article>
    <hr>
    {% if not forloop.last %}<hr>{% endif %}
    {% include 'posts/includes/paginator.html' %}  
  </div>
{% endblock %}